---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

#install packages.
library(downloader)
library(data.table)
library(plyr)
library(ggplot2)
library(AggregateR)
library(chron)

# Loading and preprocessing the data
unzip ("activity.zip")
data <- fread("activity.csv")
data$date=as.Date(data$date, "%Y-%m-%d")

## What is mean total number of steps taken per day?

# Aggregate data and create histogram
stepsperday=aggregate(steps ~ date, data, sum)
hist(stepsperday$steps, col="blue", xlab="Steps",main="Steps per day")

# Report mean
mean(stepsperday$steps)

# Report median
median(stepsperday$steps)

## What is the average daily activity pattern?

# Aggregate data and create histogram
stepsperinterval=aggregate(steps ~ interval, data, mean)
plot(stepsperinterval$interval,stepsperinterval$steps, col="red", type="l", xlab="Interval", ylab="Average Steps",main="Steps per interval")

# Report max
stepsperinterval$interval[which.max(stepsperinterval$steps)]

## Imputing missing values

# Calculate total number of missing values
sum(is.na(data))

# Merge Steps per interval average with main data
stepsperinterval=rename(stepsperinterval, c("steps"="AvgStepsInt"))
mergedata = merge(data,stepsperinterval,by.x="interval",by.y="interval")
mergedata$steps[is.na(mergedata$steps)] <- mergedata$AvgStepsInt

# Compare to no 1
# Aggregate data and create histogram
stepsperdaymod=aggregate(steps ~ date, mergedata, sum)
hist(stepsperdaymod$steps, col="blue", xlab="Steps",main="Steps per day")

# Report mean
mean(stepsperdaymod$steps)

# Report median
median(stepsperdaymod$steps)

## Are there differences in activity patterns between weekdays and weekends?
# Identify weekends
mergedata$weekend=is.weekend(mergedata$date)
weekday=subset(mergedata,mergedata$weekend==FALSE)
weekdend=subset(mergedata,mergedata$weekend==TRUE)

#create dataframes with averages per interval for each
avgweekday=aggregate(steps ~ interval, weekday, sum)
avgweekday$type="weekday"
avgweekend=aggregate(steps ~ interval, weekdend, sum)
avgweekend$type="weekend"
finalmerge=rbind(avgweekday,avgweekend)

#plot the differences
qplot(interval,steps,data=finalmerge, facets = ~ type,xlab="Interval", ylab="Steps", size=I(1), main="Steps per time of week", geom="path")

